### ISSUE TITLE
[prettier-plugin-embed] [prettier-plugin-sql] `sql.type` syntax doesn't appear to be supported

### ISSUE THREAD

**Issue by ravinggenius** [un-ts/prettier#411]
I followed the [instructions](https://github.com/un-ts/prettier/tree/master/packages/sql#sql-in-js-with-prettier-plugin-embed) for setting up prettier for embedded SQL. However I don't think my `sql` tag syntax is supported. I'm using `slonik`, so the tag is actually `sql.type`. Here's my `prettier.config.mjs` file:

```javascript
/**
 * @type {import("prettier").Config}
 */
const base = {
	plugins: [
		"@trivago/prettier-plugin-sort-imports",
		"prettier-plugin-embed",
		"prettier-plugin-sql"
	],
	importOrder: ["^@/(.*)$", "^../", "^./"],
	importOrderCaseInsensitive: true,
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	quoteProps: "consistent",
	semi: true,
	tabWidth: 4,
	useTabs: true,
	trailingComma: "none",
	overrides: [
		{
			files: ["*.json", "*.md", "*.mdx", "*.toml", "*.yaml", "*.yml"],
			options: {
				tabWidth: 2,
				useTabs: false
			}
		}
	]
};

/**
 * @type {import("prettier-plugin-embed").PluginEmbedOptions}
 */
const embed = {
	embeddedSqlTags: ["sql.fragment", "sql.type"]
};

/**
 * @type {import("prettier-plugin-sql").SqlBaseOptions}
 */
const sql = {
	keywordCase: "upper",
	language: "postgresql"
};

export default {
	...base,
	...embed,
	...sql
};
```

None of my SQL snippets are getting formatted.

**Comment by JounQin** [comment]
Please provide a runnable reproduction.

cc @Sec-ant

**Comment by ravinggenius** [comment]
Clone the project at https://github.com/ravinggenius/minecraft-tools and checkout the `prettier-prettier` branch. Install dependencies with `npm ci` and run `npm run format:fix`.

**Comment by ravinggenius** [comment]
Strangely while I was preparing the branch, I started seeing different behavior. (I don't know why, but I'll assume it was user error.) While I was originally creating this issue, I was getting the expected prettier output and no files were changed. Now I'm seeing some errors printed along with every file. Here's a sample:

```
[warn] Ignored unknown option { embeddedSqlTags: ["sql.fragment", "sql.type"] }.
[warn] Ignored unknown option { keywordCase: "upper" }.
[warn] Ignored unknown option { language: "postgresql" }.
vercel.json 0ms (unchanged)
```

SQL queries still aren't being processed.

**Comment by JounQin** [comment]
https://github.com/ravinggenius/minecraft-tools/blob/de1c1984f80fa9973ea46d86eccd58fbaa4f0896/src/domains/session/model.ts#L37-L46

I don't think `prettier-plugin-embed` support `embeddedSqlTags` like this currently.

**Comment by ravinggenius** [comment]
Yes I suppose that function returns the tag. It's going to be different for each query though.

**Comment by JounQin** [comment]
So does `sql.fragment` work as expected? If so, that means `sql.type` is a new user case for `prettier-plugin-embed`, and `embeddedSqlTags` is not suitable for this.

cc @Sec-ant

**Comment by JounQin** [comment]
Seems duplicate of https://github.com/Sec-ant/prettier-plugin-embed/issues/137

**Comment by Sec-ant** [comment]
too busy to maintain that repo because of work...😭

**Comment by JounQin** [comment]
@Sec-ant That's fine and how OS works. I may raise a PR for this issue when I'm free.

**Comment by JounQin** [comment]
@ravinggenius This has been fixed in `prettier-plugin-embbed@0.5.0`.

**Comment by ravinggenius** [comment]
Awesome! Thank you!

**Comment by ravinggenius** [comment]
I upgraded to make sure I'm using the latest version, but I'm still getting the same output as before.

```
npm ls prettier-plugin-embed
minecraft-tools@0.1.0 /Users/ravinggenius/Developer/minecraft-tools
└── prettier-plugin-embed@0.5.0
```

No files are changed, and I'm still getting the same warnings for each file:

```
[warn] Ignored unknown option { embeddedSqlTags: ["sql.type"] }.
[warn] Ignored unknown option { keywordCase: "upper" }.
[warn] Ignored unknown option { language: "postgresql" }.
src/domains/profile/model.ts 3ms (unchanged)
```

Here's the relevant section from my `prettier.config.mjs`:

```javascript
/**
 * @type {import("prettier-plugin-embed").PluginEmbedOptions}
 */
const embed = {
	embeddedSqlTags: ["sql.type"]
	// embeddedSqlTags: ["sql.fragment", "sql.type"]
};

/**
 * @type {import("prettier-plugin-sql").SqlBaseOptions}
 */
const sql = {
	keywordCase: "upper",
	language: "postgresql"
};

export default {
	...core,
	...importOrder,
	...embed,
	...sql
};
```

Am I missing something?

**Comment by JounQin** [comment]
Make sure include these two plugins in `plugins` field.

**Comment by ravinggenius** [comment]
> Make sure include these two plugins in `plugins` field.

Yeah that was it! 🤦

Thank you for getting this fixed! It appears to be working great now.
